# Name: Monika Maharjan

#  Studen ID: 230418

#4.1 Exercise on Functions:
**Task - 1:**

Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [54]:
def unit_converter():
    """
    Converts between different units of measurement.

    Conversion Types:
    - Length: meters <-> feet
    - Weight: kilograms <-> pounds
    - Volume: liters <-> gallons

    Returns:
        float: Converted value
    """

    print("Select Conversion Type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = int(input("Enter your choice (1-3): "))

        value = float(input("Enter the value to convert: "))

        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 3.28084
                print(f"{value} meters = {result} feet")
            elif option == 2:
                result = value / 3.28084
                print(f"{value} feet = {result} meters")
            else:
                print("Invalid length option.")
                return None

        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 2.20462
                print(f"{value} kg = {result} lbs")
            elif option == 2:
                result = value / 2.20462
                print(f"{value} lbs = {result} kg")
            else:
                print("Invalid weight option.")
                return None

        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 0.264172
                print(f"{value} L = {result} gallons")
            elif option == 2:
                result = value / 0.264172
                print(f"{value} gallons = {result} L")
            else:
                print("Invalid volume option.")
                return None
        else:
            print("Invalid conversion type.")
            return None

        return result

    except ValueError:
        print("Invalid input! Please enter numeric values.")
        return None


# Call function
unit_converter()

Select Conversion Type:
1. Length
2. Weight
3. Volume
Enter your choice (1-3): 2
Enter the value to convert: 30
1. Kilograms to Pounds
2. Pounds to Kilograms
Choose option: 1
30.0 kg = 66.1386 lbs


66.1386

**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [55]:
def calculate_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
        numbers (list): List of numeric values

    Returns:
        float: Sum of numbers
    """
    return sum(numbers)

In [56]:
def calculate_average(numbers):
    """
    Returns the average of numbers.

    Parameters:
        numbers (list)

    Returns:
        float: Average value
    """
    return sum(numbers) / len(numbers)

In [57]:
def find_max(numbers):
    """
    Returns maximum number from list.

    Parameters:
        numbers (list)

    Returns:
        float: Maximum value
    """
    return max(numbers)

In [58]:
def find_min(numbers):
    """
    Returns minimum number from list.

    Parameters:
        numbers (list)

    Returns:
        float: Minimum value
    """
    return min(numbers)

In [59]:
def math_operations():
    """
    Performs mathematical operations on user-input list.
    """

    try:
        print("Choose Operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = int(input("Enter choice (1-4): "))

        numbers = list(map(float, input("Enter numbers separated by space: ").split()))

        if not numbers:
            print("List is empty.")
            return

        if choice == 1:
            print("Sum:", calculate_sum(numbers))
        elif choice == 2:
            print("Average:", calculate_average(numbers))
        elif choice == 3:
            print("Maximum:", find_max(numbers))
        elif choice == 4:
            print("Minimum:", find_min(numbers))
        else:
            print("Invalid choice.")

    except ValueError:
        print("Invalid input! Please enter numeric values.")


math_operations()

Choose Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 1
Enter numbers separated by space: 2
Sum: 2.0


#4.2 Exercise on List Manipulation:
**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [60]:
def extract_every_other(lst):
    return lst[::2]

**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [61]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [62]:
def reverse_list(lst):
    return lst[::-1]

**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [63]:
def remove_first_last(lst):
    return lst[1:-1]

**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [64]:
def get_first_n(lst, n):
    return lst[:n]

**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [65]:
def get_last_n(lst, n):
    return lst[-n:]

**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [66]:
def reverse_skip(lst):
    return lst[-2::-2]

#4.3 Exercise on Nested List:

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [67]:
def flatten(lst):
    """
    Flattens a nested list (one level).
    """
    return [item for sublist in lst for item in sublist]

**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [68]:
def access_nested_element(lst, indices):
    """
    Access element from nested list using indices.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

**3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [69]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

**4. Remove Specific Element from a
Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [70]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [71]:
def find_max(lst):
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)
    return max_value

**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [72]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [73]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [74]:
def average_nested(lst):
    total = sum_nested(lst)
    count = len(deep_flatten(lst))
    return total / count

#10.1 Basic Vector and Matrix Operation with Numpy.
**Problem - 1: Array Creation:**

Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [75]:
import numpy as np
arr1 = np.empty((2,2))
arr1

array([[9.39e-323, 1.09e-322],
       [2.47e-322, 2.87e-322]])

2. Initialize an all one array with size 4X2.

In [76]:
arr2 = np.ones((4,2))
arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [77]:
arr3 = np.full((3,3), 7)
arr3

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [78]:
a = np.array([[1,2],[3,4]])
arr4 = np.zeros_like(a)
arr4

array([[0, 0],
       [0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [79]:
arr5 = np.ones_like(a)
arr5

array([[1, 1],
       [1, 1]])


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [80]:
new_list = [1,2,3,4]
arr6 = np.array(new_list)
arr6

array([1, 2, 3, 4])

**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [81]:
arr1 = np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [82]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [83]:
arr3 = np.eye(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [84]:
arr4 = np.random.random(30)
mean_value = arr4.mean()

print("Mean:", mean_value)

Mean: 0.43225294168570194


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [85]:
arr5 = np.random.random((10,10))

print("Min:", arr5.min())
print("Max:", arr5.max())

Min: 0.001578981729269624
Max: 0.9995010674999337


6. Create a zero array of size 10 and replace 5th element with 1.

In [86]:
arr6 = np.zeros(10)
arr6[4] = 1   # 5th element (index 4)
arr6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Reverse an array arr = [1,2,0,0,4,0].

In [87]:
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
reversed_arr

array([0, 4, 0, 0, 2, 1])

8. Create a 2d array with 1 on border and 0 inside.

In [88]:
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
arr8

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [89]:
arr9 = np.zeros((8,8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
arr9

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.

In [90]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

x + y

array([[ 6,  8],
       [10, 13]])

In [91]:
v + w

array([20, 22])

2. Subtract the two array.

In [92]:
v - w

array([-2, -2])

In [93]:
x - y

array([[-4, -4],
       [-4, -3]])

3. Multiply the array with any integers of your choice.

In [94]:
x*3

array([[ 3,  6],
       [ 9, 15]])

In [95]:
y*4

array([[20, 24],
       [28, 32]])

In [96]:
v*9

array([81, 90])

In [97]:
w*0

array([0, 0])

4. Find the square of each element of the array.

In [98]:
np.square(x)

array([[ 1,  4],
       [ 9, 25]])

In [99]:
np.square(y)

array([[25, 36],
       [49, 64]])

In [100]:
np.square(v)

array([ 81, 100])

In [101]:
np.square(w)

array([121, 144])

5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [102]:
print("v.w =", np.dot(v,w))
print("x.v =", np.dot(x,v))
print("x.y =", np.dot(x,y))

v.w = 219
x.v = [29 77]
x.y = [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [103]:
np.vstack((x,y))

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [104]:
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [106]:
np.vstack((x,v))

array([[ 1,  2],
       [ 3,  5],
       [ 9, 10]])

Because the dimensions do not match, x is 2D and v is 1D.

**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.


In [107]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [108]:
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
identity

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

2. Prove AB ̸= BA.

In [109]:
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


3. Prove (AB)T = BTAT

In [110]:
AB = np.dot(A,B)

left = AB.T
right = np.dot(B.T, A.T)

print("Left:\n", left)
print("Right:\n", right)

Left:
 [[23 51]
 [13 29]]
Right:
 [[23 51]
 [13 29]]



• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}


In [111]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

In [113]:
detA = np.linalg.det(A)
detA

np.float64(-19.000000000000004)

In [112]:
cofactor = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
        cofactor[i][j] = ((-1)**(i+j)) * np.linalg.det(minor)

adjA = cofactor.T

In [114]:
A_inv = (1/detA) * adjA
A_inv

array([[ 0.05263158,  0.10526316,  0.26315789],
       [-0.36842105,  0.26315789,  0.15789474],
       [-0.21052632,  0.57894737, -0.05263158]])

In [115]:
X = np.dot(A_inv, B)
X

array([ 2.,  1., -2.])

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [116]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([ 2.,  1., -2.])

#10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [118]:
import time

In [119]:
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end = time.time()

print("Python List Addition Time:", end - start)

Python List Addition Time: 0.20223188400268555


In [120]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result = arr1 + arr2
end = time.time()

print("NumPy Addition Time:", end - start)

NumPy Addition Time: 0.022018909454345703


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [121]:
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end = time.time()

print("Python Multiplication Time:", end - start)

Python Multiplication Time: 0.11897015571594238


In [122]:
start = time.time()
result = arr1 * arr2
end = time.time()

print("NumPy Multiplication Time:", end - start)

NumPy Multiplication Time: 0.018031835556030273


**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [123]:
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
end = time.time()

print("Python Dot Product Time:", end - start)

Python Dot Product Time: 0.10719084739685059


In [124]:
start = time.time()
dot = np.dot(arr1, arr2)
end = time.time()

print("NumPy Dot Product Time:", end - start)

NumPy Dot Product Time: 0.003045320510864258


**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [125]:
import random

size = 1000
A = [[random.random() for _ in range(size)] for _ in range(size)]
B = [[random.random() for _ in range(size)] for _ in range(size)]

start = time.time()

result = [[sum(A[i][k] * B[k][j] for k in range(size))
           for j in range(size)]
           for i in range(size)]

end = time.time()
print("Python Matrix Multiplication Time:", end - start)

Python Matrix Multiplication Time: 212.12294220924377


In [126]:
A = np.random.random((1000,1000))
B = np.random.random((1000,1000))

start = time.time()
result = np.dot(A,B)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

NumPy Matrix Multiplication Time: 0.08612275123596191
